
class Settings:
    SMS_DB_HOST = "YOUR_SMS_DB_HOST"
    SMS_DB_USER = "YOUR_SMS_DB_USER"
    SMS_DB_PASSWORD = "YOUR_SMS_DB_PASSWORD"
    SMS_DB_NAME = "YOUR_SMS_DB_NAME"

    SMTP_SERVER = "YOUR_SMTP_SERVER"
    SMTP_PORT = 25
    SENDER_EMAIL = "YOUR_SENDER_EMAIL"
    PASSWORD = "YOUR_PASSWORD"

settings = Settings()