# Generated by Django 5.2.1 on 2025-09-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='down', max_length=20),
        ),
    ]
