# Generated by Django 5.2.8 on 2026-01-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_phone_profile_city_profile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='کاربر بدون نام', max_length=120),
        ),
    ]
