# Generated by Django 5.2.1 on 2025-10-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_domainaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainaction',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
