# Generated by Django 5.2.1 on 2025-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('record_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('attacghment', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('createsd_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
