# Generated by Django 5.2.1 on 2025-10-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='attacghment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
