# Generated by Django 5.2.1 on 2025-10-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_financialrecord_attacghment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='attacghment',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
