# Generated by Django 5.2.1 on 2025-10-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_financialrecord_attacghment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialrecord',
            old_name='createsd_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='attacghment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
