# Generated by Django 5.2.1 on 2026-02-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_rename_createsd_at_financialrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='record_date',
            field=models.CharField(max_length=10),
        ),
    ]
