# Generated by Django 5.2.1 on 2026-02-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_financialrecord_record_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialrecord',
            old_name='attacghment',
            new_name='attachment',
        ),
    ]
